# Generated by Django 6.0.3 on 2026-03-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spreadsheets", "0002_spreadsheets_engine_alignment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spreadsheetsheet",
            options={},
        ),
        migrations.AlterModelOptions(
            name="spreadsheetversion",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="spreadsheetbinding",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="spreadsheetsheet",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="spreadsheetversion",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="spreadsheetaianalysis",
            name="result",
        ),
        migrations.RemoveField(
            model_name="spreadsheetexportjob",
            name="summary",
        ),
        migrations.RemoveField(
            model_name="spreadsheetmapping",
            name="mapping",
        ),
        migrations.RemoveField(
            model_name="spreadsheetstylesnapshot",
            name="column_widths",
        ),
        migrations.RemoveField(
            model_name="spreadsheetstylesnapshot",
            name="conditional_formats",
        ),
        migrations.RemoveField(
            model_name="spreadsheetstylesnapshot",
            name="data_validations",
        ),
        migrations.RemoveField(
            model_name="spreadsheetstylesnapshot",
            name="filters",
        ),
        migrations.RemoveField(
            model_name="spreadsheetstylesnapshot",
            name="freeze_panes",
        ),
        migrations.RemoveField(
            model_name="spreadsheetstylesnapshot",
            name="merged_ranges",
        ),
        migrations.RemoveField(
            model_name="spreadsheetstylesnapshot",
            name="row_heights",
        ),
        migrations.RemoveField(
            model_name="spreadsheetstylesnapshot",
            name="style",
        ),
        migrations.RemoveField(
            model_name="spreadsheetsyncjob",
            name="summary",
        ),
        migrations.AddField(
            model_name="spreadsheetaianalysis",
            name="result_json",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="spreadsheetdocument",
            name="checksum",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="spreadsheetdocument",
            name="metadata_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="spreadsheetexportjob",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="spreadsheetexportjob",
            name="summary_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="spreadsheetmapping",
            name="mapping_json",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="spreadsheetsheet",
            name="detected_table_ranges_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="spreadsheetsheet",
            name="metadata_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="spreadsheetstylesnapshot",
            name="column_widths_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="spreadsheetstylesnapshot",
            name="conditional_formats_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="spreadsheetstylesnapshot",
            name="data_validations_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="spreadsheetstylesnapshot",
            name="filters_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="spreadsheetstylesnapshot",
            name="freeze_panes_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="spreadsheetstylesnapshot",
            name="merged_ranges_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="spreadsheetstylesnapshot",
            name="row_heights_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="spreadsheetstylesnapshot",
            name="style_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="spreadsheetsyncjob",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="spreadsheetsyncjob",
            name="summary_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="spreadsheetversion",
            name="metadata_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="spreadsheetaianalysis",
            name="analysis_type",
            field=models.CharField(
                choices=[
                    ("mapping_suggestion", "Mapping suggestion"),
                    ("anomaly_report", "Anomaly report"),
                    ("formula_explanation", "Formula explanation"),
                    ("sync_recommendation", "Sync recommendation"),
                ],
                db_index=True,
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="spreadsheetaianalysis",
            name="confidence",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="spreadsheetaianalysis",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="spreadsheetbinding",
            name="binding_key",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="spreadsheetbinding",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="spreadsheetbinding",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("deal", "Deal"),
                    ("task", "Task"),
                    ("activity", "Activity"),
                    ("custom", "Custom"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="spreadsheetdocument",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="spreadsheetdocument",
            name="mime_type",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="spreadsheetdocument",
            name="original_filename",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="spreadsheetdocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("analyzing", "Analyzing"),
                    ("ready", "Ready"),
                    ("sync_error", "Sync error"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="uploaded",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="spreadsheetdocument",
            name="storage_key",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="spreadsheetdocument",
            name="uploaded_by_user_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="spreadsheetexportjob",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="spreadsheetexportjob",
            name="output_storage_key",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="spreadsheetexportjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("partial", "Partial"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="spreadsheetmapping",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="spreadsheetmapping",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("deal", "Deal"),
                    ("task", "Task"),
                    ("activity", "Activity"),
                    ("custom", "Custom"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="spreadsheetmapping",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="spreadsheetmapping",
            name="range_ref",
            field=models.CharField(help_text="Example: A1:F200", max_length=64),
        ),
        migrations.AlterField(
            model_name="spreadsheetmapping",
            name="sync_mode",
            field=models.CharField(
                choices=[
                    ("import_only", "Import only"),
                    ("export_only", "Export only"),
                    ("bidirectional", "Bidirectional"),
                    ("template_only", "Template only"),
                ],
                db_index=True,
                default="import_only",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="spreadsheetsheet",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="spreadsheetstylesnapshot",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="spreadsheetstylesnapshot",
            name="range_ref",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="spreadsheetsyncjob",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="spreadsheetsyncjob",
            name="direction",
            field=models.CharField(
                choices=[
                    ("to_db", "To DB"),
                    ("from_db", "From DB"),
                    ("bidirectional", "Bidirectional"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="spreadsheetsyncjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("partial", "Partial"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="spreadsheetversion",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="spreadsheetversion",
            name="created_by_user_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="spreadsheetversion",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("regenerated", "Regenerated"),
                    ("synced_from_db", "Synced from DB"),
                    ("ai_modified", "AI modified"),
                ],
                db_index=True,
                default="uploaded",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="spreadsheetversion",
            name="storage_key",
            field=models.CharField(max_length=1024),
        ),
        migrations.AddIndex(
            model_name="spreadsheetaianalysis",
            index=models.Index(
                fields=["document", "analysis_type", "created_at"],
                name="spreadsheet_documen_5d755e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="spreadsheetaianalysis",
            index=models.Index(
                fields=["version", "analysis_type"],
                name="spreadsheet_version_63caa9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="spreadsheetbinding",
            index=models.Index(
                fields=["mapping", "sheet_name", "row_index"],
                name="spreadsheet_mapping_94e0e6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="spreadsheetbinding",
            index=models.Index(
                fields=["entity_type", "entity_id"],
                name="spreadsheet_entity__bf3583_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="spreadsheetdocument",
            index=models.Index(
                fields=["organization_id", "status"],
                name="spreadsheet_organiz_927954_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="spreadsheetdocument",
            index=models.Index(
                fields=["organization_id", "created_at"],
                name="spreadsheet_organiz_62df19_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="spreadsheetexportjob",
            index=models.Index(
                fields=["organization_id", "status", "created_at"],
                name="spreadsheet_organiz_95b97a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="spreadsheetexportjob",
            index=models.Index(
                fields=["document", "created_at"], name="spreadsheet_documen_d010ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="spreadsheetmapping",
            index=models.Index(
                fields=["organization_id", "entity_type", "is_active"],
                name="spreadsheet_organiz_2e491a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="spreadsheetmapping",
            index=models.Index(
                fields=["document", "sheet_name"], name="spreadsheet_documen_37964a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="spreadsheetsheet",
            index=models.Index(
                fields=["version", "position"], name="spreadsheet_version_ce3b11_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="spreadsheetstylesnapshot",
            index=models.Index(
                fields=["version", "sheet_name"], name="spreadsheet_version_41ca20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="spreadsheetsyncjob",
            index=models.Index(
                fields=["organization_id", "status", "created_at"],
                name="spreadsheet_organiz_804737_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="spreadsheetsyncjob",
            index=models.Index(
                fields=["document", "created_at"], name="spreadsheet_documen_ba52c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="spreadsheetversion",
            index=models.Index(
                fields=["document", "version_number"],
                name="spreadsheet_documen_cb4b4f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="spreadsheetversion",
            index=models.Index(
                fields=["document", "created_at"], name="spreadsheet_documen_ef57cb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="spreadsheetbinding",
            constraint=models.UniqueConstraint(
                fields=("mapping", "sheet_name", "row_index"),
                name="uq_spreadsheet_binding_row_per_mapping",
            ),
        ),
        migrations.AddConstraint(
            model_name="spreadsheetbinding",
            constraint=models.UniqueConstraint(
                fields=("mapping", "binding_key"),
                name="uq_spreadsheet_binding_key_per_mapping",
            ),
        ),
        migrations.AddConstraint(
            model_name="spreadsheetsheet",
            constraint=models.UniqueConstraint(
                fields=("version", "name"), name="uq_spreadsheet_sheet_name_per_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="spreadsheetsheet",
            constraint=models.UniqueConstraint(
                fields=("version", "position"),
                name="uq_spreadsheet_sheet_position_per_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="spreadsheetversion",
            constraint=models.UniqueConstraint(
                fields=("document", "version_number"),
                name="uq_spreadsheet_version_per_document",
            ),
        ),
        migrations.AlterModelTable(
            name="spreadsheetaianalysis",
            table="spreadsheet_ai_analyses",
        ),
        migrations.AlterModelTable(
            name="spreadsheetbinding",
            table="spreadsheet_bindings",
        ),
        migrations.AlterModelTable(
            name="spreadsheetdocument",
            table="spreadsheet_documents",
        ),
        migrations.AlterModelTable(
            name="spreadsheetexportjob",
            table="spreadsheet_export_jobs",
        ),
        migrations.AlterModelTable(
            name="spreadsheetmapping",
            table="spreadsheet_mappings",
        ),
        migrations.AlterModelTable(
            name="spreadsheetsheet",
            table="spreadsheet_sheets",
        ),
        migrations.AlterModelTable(
            name="spreadsheetstylesnapshot",
            table="spreadsheet_style_snapshots",
        ),
        migrations.AlterModelTable(
            name="spreadsheetsyncjob",
            table="spreadsheet_sync_jobs",
        ),
        migrations.AlterModelTable(
            name="spreadsheetversion",
            table="spreadsheet_versions",
        ),
        migrations.RemoveField(
            model_name="spreadsheetsheet",
            name="detected_table_ranges",
        ),
        migrations.RemoveField(
            model_name="spreadsheetsheet",
            name="metadata",
        ),
    ]
